version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: norbin/techmesh:0.0.4
    steps:
      - checkout
      - run: 
          name: "echo an env var that is part of our project"
          command: |
            echo $NON_PROD_AWS_ACCESS_KEY_ID # this env var must be set within the project