version: 2.1

workflows:
  validate:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: norbin/techmesh:0.0.4
    steps:
      - run:
          name: "configure aws credentials"
          command: |
            export AWS_ACCESS_KEY_ID=$NON_PROD_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$NON_PROD_AWS_SECRET_ACCESS_KEY
      - checkout
      - run: 
          name: "init && fmt"
          command: |
            cd ./terragrunt/non-prod/us-east-1/dev/mesh
            terragrunt fmt ~/project/terraform